from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time 

options = webdriver.EdgeOptions();
options.add_experimental_option("detach", True)

service_object = Service()
driver = webdriver.Chrome(service=service_object, options=options)


driver.get("http://localhost/WEB_Project_Disaster-Relief-Camp-Volunteer-Coordination-System_-Team-SiteMasters/index.php")
driver.maximize_window()
time.sleep(1)
driver.find_element(By.LINK_TEXT,"Sign In").click();
time.sleep(1)
driver.find_element(By.NAME, "email").send_keys("admin@gmail.com")
time.sleep(1)
driver.find_element(By.NAME, "password").send_keys("123456")
time.sleep(1)
driver.find_element(By.CLASS_NAME,"btn-signin").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Camp Managers')]").click()
time.sleep(1)
driver.find_element(By.CLASS_NAME,"btn-primary").click()
time.sleep(1)
driver.find_element(By.NAME, "full_name").send_keys("jisan")
time.sleep(1)
driver.find_element(By.NAME, "email").send_keys("jisan@gmail.com")
time.sleep(1)
driver.find_element(By.NAME, "phone").send_keys("11111111111")
time.sleep(1)
driver.find_element(By.NAME, "password").send_keys("1234")
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='addManagerModal']//input[@name='location']").send_keys("Dhaka")
time.sleep(1)
driver.find_element(By.NAME, "camp_id").click()
time.sleep(1)
driver.find_element(By.NAME, "camp_id").click()
time.sleep(1)
driver.find_element(By.XPATH, "//select[@name='camp_id']/option[text()='Camp Alpha (Sylhet)']").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='addManagerModal']//button[text()='Add Manager']").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Camps')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//button[text()='Edit']").click()
capacity_input = driver.find_element(By.ID, "edit_capacity")
capacity_input.clear()
time.sleep(1) # Optional: wait a moment for the clear to complete
capacity_input.send_keys("600")
# Save Changes button
driver.find_element(By.XPATH, "//div[@id='editCampModal']//button[text()='Save Changes']").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Volunteers')]").click()
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, ".btn-reject").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Donors')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Donations')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Task Assignment')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//button[contains(text(), 'Assign New Task')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[@id='addTaskModal']//button[text()='Cancel']").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Inventory')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Support Chat')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//tr[contains(., 'Tanvir Ahmed')]//a[contains(text(), 'Open Chat')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//button[contains(., 'Admin User')]").click()
time.sleep(1)
driver.find_element(By.XPATH, "//a[contains(text(), 'Log Out')]").click()
time.sleep(1)

